name: mypy

on:
  workflow_call:
    inputs:
      poetry-version:
        description: 'Poetry version to be used'
        required: true
        type: string

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    env:
      MYPY_CACHE_DIR: ~/.cache/mypy
    steps:
      - uses: actions/checkout@v4
      - name: Set up poetry ${{ inputs.poetry-version }}
        run: pipx install poetry==${{ inputs.poetry-version }}
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - uses: actions/cache@v4
        with:
          path: ${{ env.MYPY_CACHE_DIR }}
          key: mypy-${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Run Mypy
        run: poetry run mypy
